sonar.projectKey=your-project-key
sonar.organization=your-org

sonar.sources=src
sonar.tests=tests

sonar.cs.opencover.reportsPaths=**/coverage.cobertura.xml
sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**
sonar.test.exclusions=tests/**
